# Generated by Django 3.0.4 on 2020-03-30 09:23

from django.db import migrations, models
import jedzonko.enums


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeplan',
            name='day_name',
            field=models.CharField(choices=[(jedzonko.enums.Dayname['MONDAY'], 1), (jedzonko.enums.Dayname['TUESDAY'], 2), (jedzonko.enums.Dayname['WEDNESDAY'], 3), (jedzonko.enums.Dayname['THURSDAY'], 4), (jedzonko.enums.Dayname['FRIDAY'], 5), (jedzonko.enums.Dayname['SATURDAY'], 6), (jedzonko.enums.Dayname['SUNDAY'], 7)], max_length=20),
        ),
    ]
