# Generated by Django 3.0.4 on 2020-03-31 02:40

from django.db import migrations
from jedzonko.models import DayName


def dayname_migrate(apps, schema_editor):
    DayName.objects.create(day_name="Poniedziałek", order=1)
    DayName.objects.create(day_name="Wtorek", order=2)
    DayName.objects.create(day_name="Środa", order=3)
    DayName.objects.create(day_name="Czwartek", order=4)
    DayName.objects.create(day_name="Piątek", order=5)
    DayName.objects.create(day_name="Sobota", order=6)
    DayName.objects.create(day_name="Niedziela", order=7)

class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0003_auto_20200331_0323'),
    ]

    operations = [
        migrations.RunPython(dayname_migrate),
    ]
