# Generated by Django 3.0.4 on 2020-03-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0005_auto_20200331_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation_details',
            field=models.TextField(default=''),
        ),
    ]
