# Generated by Django 3.0.5 on 2020-04-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0006_recipe_preparation_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=16)),
                ('order', models.IntegerField(unique=True)),
            ],
        ),
    ]
