# Generated by Django 3.0.5 on 2020-04-19 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0007_day_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day_test',
        ),
    ]
